import Head from "next/head";

import { Inter } from "next/font/google";
import { Flex, Box, Button } from "@chakra-ui/react";
import About from "./about";
import Contact from "./contact";
import HomeComponent from "./Home";
import NavigationBar from "@/components/NavBarComponent/NavBarContainer";
import Recipes from "./Recipes";
import Footer from "@/components/FooterComponent/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
      
        <Flex direction="column">
          <NavigationBar />
          <Box bg="#f7ecdf">
            <HomeComponent idName={"Home"} />
          </Box>
          <Box backgroundColor="#f7ecdf">
            <About idName={"about"} />
          </Box>

          <Box bg="#FED0D0">
            <Recipes idName={"Recipes"} />
          </Box>
          <Box display='flex' flexDirection='column' justifyContent='space-around'>
            <Contact idName={"contact"} />
           
          </Box>
          
        </Flex>
      </main>
    </>
  );
}
